version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'nimble-factor-451317-n3') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'trips_data_all') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}

     